name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: ["**"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        job: [linux-node-latest]
        include:
          - job: linux-node-latest
            os: ubuntu-latest
            node: 14.x
            browsers: chrome, chrome-headless, firefox, firefox-headless

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js (${{ matrix.node }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install
        run: npm install

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
